In [1]:
import torch

In [2]:
#创建一个(2,3)的tensor
a = torch.randn(2,3)
a.type()

'torch.FloatTensor'

In [3]:
type(a)

torch.Tensor

In [4]:
isinstance(a, torch.FloatTensor)

True

In [10]:
data = a
isinstance(data, torch.cuda.FloatTensor)

False

In [11]:
data = data.cuda()
isinstance(data, torch.cuda.FloatTensor)

True

In [12]:
torch.tensor(1.)

tensor(1.)

In [13]:
torch.tensor(1.3)

tensor(1.3000)

In [14]:
a = torch.tensor(2.2)
a.shape

torch.Size([])

In [15]:
len(a.shape)

0

In [16]:
a.size()

torch.Size([])

In [17]:
torch.tensor([1.1])

tensor([1.1000])

In [18]:
torch.tensor([1.1,2.2])

tensor([1.1000, 2.2000])

In [20]:
torch.FloatTensor(1)

tensor([0.])

In [21]:
torch.FloatTensor(2)

tensor([3.1267e+07, 4.5908e-41])

In [25]:
import numpy as np
data = np.ones(2)
data

array([1., 1.])

In [26]:
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

In [28]:
a = torch.ones(2)
a.shape

torch.Size([2])

In [29]:
a = torch.randn(2,3)
a

tensor([[ 0.3429,  0.4041, -0.4574],
        [-0.3314, -0.8517,  0.3350]])

In [30]:
a.shape

torch.Size([2, 3])

In [31]:
a.size()

torch.Size([2, 3])

In [32]:
a.size(0)

2

In [33]:
a.size(1)

3

In [34]:
a.shape[1]

3

In [35]:
a = torch.rand(1,2,3)
a

tensor([[[0.8617, 0.3860, 0.4491],
         [0.9014, 0.7236, 0.5982]]])

In [36]:
a.shape

torch.Size([1, 2, 3])

In [37]:
a[0]

tensor([[0.8617, 0.3860, 0.4491],
        [0.9014, 0.7236, 0.5982]])

In [38]:
list(a.shape)

[1, 2, 3]

In [39]:
a = torch.rand(2, 3, 28, 28)
a

tensor([[[[0.4956, 0.6083, 0.5764,  ..., 0.4375, 0.2508, 0.3846],
          [0.8637, 0.6947, 0.0570,  ..., 0.1183, 0.5860, 0.9257],
          [0.1583, 0.0888, 0.8493,  ..., 0.0894, 0.3008, 0.3605],
          ...,
          [0.1599, 0.0716, 0.3109,  ..., 0.4213, 0.0721, 0.3324],
          [0.7416, 0.2268, 0.8765,  ..., 0.8080, 0.4763, 0.2671],
          [0.9307, 0.4015, 0.3792,  ..., 0.6910, 0.9646, 0.2809]],

         [[0.7785, 0.8726, 0.4803,  ..., 0.7286, 0.0045, 0.2800],
          [0.0476, 0.3775, 0.5885,  ..., 0.7910, 0.9291, 0.8005],
          [0.6451, 0.3638, 0.3020,  ..., 0.7345, 0.6503, 0.5509],
          ...,
          [0.5314, 0.8654, 0.8299,  ..., 0.2538, 0.5443, 0.9638],
          [0.7160, 0.0043, 0.8817,  ..., 0.6772, 0.0217, 0.7311],
          [0.2591, 0.8414, 0.5247,  ..., 0.6219, 0.4309, 0.2890]],

         [[0.3353, 0.4619, 0.7787,  ..., 0.2436, 0.7511, 0.5746],
          [0.6993, 0.3319, 0.0382,  ..., 0.1982, 0.0997, 0.0272],
          [0.8187, 0.5706, 0.9838,  ..., 0

In [40]:
a.shape

torch.Size([2, 3, 28, 28])

In [41]:
a.numel()

4704

In [42]:
a.dim()

4

In [43]:
a = torch.tensor(1)
a.dim()

0