In [1]:
import torch
import numpy as np

In [2]:
a = np.array([2,3.3])
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [3]:
a = np.ones([2,3])
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [4]:
torch.tensor([2,3.2])

tensor([2.0000, 3.2000])

In [5]:
torch.FloatTensor([2.,3.2])

tensor([2.0000, 3.2000])

In [6]:
torch.tensor([[2.,3.4],[1.3,3.4]])

tensor([[2.0000, 3.4000],
        [1.3000, 3.4000]])

In [9]:
# torch.Tensor() 等同于 torch.FloatTensor()
torch.Tensor(2,3)

tensor([[7.1746e-43, 0.0000e+00, 7.1746e-43],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [8]:
torch.FloatTensor(2,3)

tensor([[1.1995e-42, 0.0000e+00, 1.1995e-42],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])

建议(默认均为FloatTensor类型)：
* 用小写tensor创建具体数据
* 用大写Tensor或FloatTensor创建指定维度的数据(创建出来的数据均未初始化uninitialized)

In [10]:
torch.empty(2,3)

tensor([[6.1895e+35, 4.4141e-43, 0.0000e+00],
        [0.0000e+00, 1.8367e-40, 0.0000e+00]])

In [12]:
torch.IntTensor(1,5,5)

tensor([[[2086986104,        315,         64,          0,          0],
         [         0,          0,          0,          0,          0],
         [ 878785078,  862204006, 1664234809,  845439843,  859399736],
         [ 875770420, 1681076281, 1647456614,  892625250, 1664103526],
         [ 862283064,  828584548,  808597047,  859267941, 1664235873]]],
       dtype=torch.int32)

In [13]:
torch.tensor([1.2,3]).type()

'torch.FloatTensor'

In [14]:
#设置默认类型为DoubleTensor
torch.set_default_tensor_type(torch.DoubleTensor)

In [15]:
torch.tensor([1.2,3]).type()

'torch.DoubleTensor'

# 创建随机数据

In [17]:
# [0,1]
torch.rand(3,3)

tensor([[0.2625, 0.5998, 0.3680],
        [0.3858, 0.8196, 0.8575],
        [0.1038, 0.9118, 0.5094]])

In [18]:
# 根据传入的张量形状，生成随机数据
a = torch.rand(3,3)
torch.rand_like(a)

tensor([[0.1927, 0.3027, 0.8175],
        [0.1808, 0.2680, 0.4242],
        [0.3963, 0.6881, 0.1847]])

In [20]:
#指定范围[1,10]
torch.randint(1,10,(3,3))

tensor([[9, 6, 2],
        [1, 2, 3],
        [2, 4, 4]])

In [21]:
#随机数据符合0、1标准正态分布
torch.randn(3,3)

tensor([[-0.0579,  0.0191,  0.4892],
        [-0.3283, -1.4944, -0.5897],
        [ 0.1735, -2.0045,  0.2863]])

In [22]:
#自定义均值和方差
#torch.full([10],0)   -->  [0,0,0,...,0]
torch.normal(mean = torch.full([10], 0), std = torch.arange(1, 0, -0.1))

tensor([-0.4624,  0.8098,  0.7821, -0.1325,  0.9742, -0.0778, -1.0148,  0.0129,
         0.2067,  0.0510])

In [23]:
torch.full([2,3],7)

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [24]:
torch.full((2,3),7)

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [25]:
torch.full([],7)

tensor(7.)

In [28]:
torch.full([3],7)

tensor([7., 7., 7.])

# 创建序列

In [30]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

# 生成等分数据

In [33]:
torch.linspace(0,10,4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [35]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [36]:
torch.linspace(0,10,11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
# [10^0,10^1,10^2,...10^10]
torch.logspace(0,10,11)

tensor([1.0000e+00, 1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05,
        1.0000e+06, 1.0000e+07, 1.0000e+08, 1.0000e+09, 1.0000e+10])

In [38]:
torch.logspace(0,-1,2)

tensor([1.0000, 0.1000])

# 其他常用矩阵

In [41]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [42]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [43]:
#单位矩阵
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [44]:
a = torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [45]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

# 其他

In [46]:
#生成序列数据后将其打散
torch.randperm(10)

tensor([0, 6, 5, 7, 1, 3, 2, 9, 4, 8])

In [48]:
torch.randperm(5)

tensor([2, 3, 0, 1, 4])

In [60]:
a = torch.rand(5,3)
b = torch.rand(5,2)
idx = torch.randperm(5)
idx

tensor([4, 0, 2, 1, 3])

In [61]:
a

tensor([[0.3211, 0.4154, 0.6344],
        [0.5447, 0.5019, 0.9740],
        [0.1451, 0.9873, 0.5473],
        [0.7145, 0.2271, 0.8775],
        [0.5528, 0.7883, 0.8013]])

In [62]:
a[idx]

tensor([[0.5528, 0.7883, 0.8013],
        [0.3211, 0.4154, 0.6344],
        [0.1451, 0.9873, 0.5473],
        [0.5447, 0.5019, 0.9740],
        [0.7145, 0.2271, 0.8775]])

In [63]:
b

tensor([[0.9592, 0.6767],
        [0.4555, 0.0455],
        [0.7584, 0.1729],
        [0.0164, 0.4868],
        [0.5070, 0.1225]])

In [64]:
b[idx]

tensor([[0.5070, 0.1225],
        [0.9592, 0.6767],
        [0.7584, 0.1729],
        [0.4555, 0.0455],
        [0.0164, 0.4868]])