In [1]:
import torch

In [3]:
a = torch.full([4], 1/4)
a

tensor([0.2500, 0.2500, 0.2500, 0.2500])

In [4]:
a*torch.log2(a)

tensor([-0.5000, -0.5000, -0.5000, -0.5000])

In [6]:
-(a*torch.log2(a)).sum()

tensor(2.)

In [7]:
a = torch.tensor([0.1,0.1,0.1,0.7])
a

tensor([0.1000, 0.1000, 0.1000, 0.7000])

In [8]:
-(a*torch.log2(a)).sum()

tensor(1.3568)

In [10]:
a = torch.tensor([0.001,0.001,0.001,0.999])
-(a*torch.log2(a)).sum()

tensor(0.0114)