In [4]:
import torch
import torch.nn.functional as F

In [2]:
x = torch.randn(1,784)
w = torch.randn(10,784)

In [14]:
logits = x@w.t()
logits

tensor([[  7.6985,  48.9292,  -0.5096, -37.4636,   0.4461,   1.4190, -55.6647,
         -11.4621,  -0.4208,   0.6016]])

In [15]:
pred = F.softmax(logits, dim=1)
pred

tensor([[1.2409e-18, 1.0000e+00, 3.3806e-22, 3.0206e-38, 8.7918e-22, 2.3259e-21,
         0.0000e+00, 5.9209e-27, 3.6947e-22, 1.0271e-21]])

In [16]:
pred_log = torch.log(pred)
pred_log

tensor([[-41.2307,   0.0000, -49.4388, -86.3928, -48.4830, -47.5102,     -inf,
         -60.3913, -49.3500, -48.3276]])

In [8]:
F.cross_entropy(logits, torch.tensor([3]))

tensor(86.3928)

In [10]:
F.nll_loss(pred_log, torch.tensor([3]))

tensor(86.3928)