statisics:
- norm
- mean sum
- prod
- max, min, argmin. argmax
- kthvalue, topk

In [1]:
import torch

In [2]:
a = torch.full([8], 1)
b = a.view(2,4)
c = a.view(2,2,2)
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [3]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [4]:
a.norm(1), b.norm(1), c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [5]:
a.norm(2), b.norm(2), c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [6]:
b.norm(1, dim=1)

tensor([4., 4.])

In [7]:
b.norm(2, dim=1)

tensor([2., 2.])

In [10]:
c.norm(1, dim=0)

tensor([[2., 2.],
        [2., 2.]])

In [9]:
c.norm(2, dim=0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

In [16]:
a = torch.arange(1,9).view(2,4).float()

In [17]:
a

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [18]:
a.min(), a.max(), a.mean(), a.prod()

(tensor(1.), tensor(8.), tensor(4.5000), tensor(40320.))

In [19]:
a.sum(),a.argmax(),a.argmin()

(tensor(36.), tensor(7), tensor(0))

In [20]:
a = torch.randn(4,10)
a[0]

tensor([-0.2401,  0.0278,  0.0211,  0.1805,  0.5472, -0.1385,  0.4061, -2.1645,
        -0.9038,  2.0166])

In [23]:
a.argmax(dim=1)

tensor([9, 5, 4, 6])

In [24]:
a

tensor([[-0.2401,  0.0278,  0.0211,  0.1805,  0.5472, -0.1385,  0.4061, -2.1645,
         -0.9038,  2.0166],
        [ 0.2867,  0.1951,  0.6751, -0.0270, -0.2087,  1.2618,  0.4536, -0.9001,
         -1.1048, -0.2534],
        [-0.2606,  0.5195, -1.1699, -1.3371,  1.7214,  0.1009,  0.5204,  0.1234,
          1.5112, -0.3286],
        [ 0.9213, -1.7516,  0.7981, -0.3252,  0.8209,  1.1996,  1.8481,  1.1376,
         -1.7185, -0.7256]])

In [27]:
a.max(dim=1)

(tensor([2.0166, 1.2618, 1.7214, 1.8481]), tensor([9, 5, 4, 6]))

In [28]:
a.argmax(dim=1)

tensor([9, 5, 4, 6])

In [29]:
a.max(dim=1,keepdim=True)

(tensor([[2.0166],
         [1.2618],
         [1.7214],
         [1.8481]]),
 tensor([[9],
         [5],
         [4],
         [6]]))

In [30]:
a.argmax(dim=1,keepdim=True)

tensor([[9],
        [5],
        [4],
        [6]])

In [31]:
#返回最大，次大，第三大，... 第n大的数据
a.topk(3,dim=1)

(tensor([[2.0166, 0.5472, 0.4061],
         [1.2618, 0.6751, 0.4536],
         [1.7214, 1.5112, 0.5204],
         [1.8481, 1.1996, 1.1376]]),
 tensor([[9, 4, 6],
         [5, 2, 6],
         [4, 8, 6],
         [6, 5, 7]]))

In [32]:
#返回最小，次小，第三小，... 第n小的数据
a.topk(3,dim=1,largest=False)

(tensor([[-2.1645, -0.9038, -0.2401],
         [-1.1048, -0.9001, -0.2534],
         [-1.3371, -1.1699, -0.3286],
         [-1.7516, -1.7185, -0.7256]]),
 tensor([[7, 8, 0],
         [8, 7, 9],
         [3, 2, 9],
         [1, 8, 9]]))

In [33]:
#返回第n小的数据
a.kthvalue(8,dim=1)

(tensor([0.4061, 0.4536, 0.5204, 1.1376]), tensor([6, 6, 6, 7]))

In [34]:
a.kthvalue(3,dim=1)

(tensor([-0.2401, -0.2534, -0.3286, -0.7256]), tensor([0, 9, 9, 9]))

In [35]:
a.kthvalue(3)

(tensor([-0.2401, -0.2534, -0.3286, -0.7256]), tensor([0, 9, 9, 9]))

In [36]:
a>0

tensor([[0, 1, 1, 1, 1, 0, 1, 0, 0, 1],
        [1, 1, 1, 0, 0, 1, 1, 0, 0, 0],
        [0, 1, 0, 0, 1, 1, 1, 1, 1, 0],
        [1, 0, 1, 0, 1, 1, 1, 1, 0, 0]], dtype=torch.uint8)

In [37]:
a!=0

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.uint8)

# 高级操作

In [39]:
cond = torch.randn([2,2])

In [40]:
cond

tensor([[ 0.2363,  0.3039],
        [-1.1741, -0.5124]])

In [44]:
a = torch.randn([2,2])
b = torch.randn([2,2])

In [45]:
a

tensor([[-0.0753,  0.1795],
        [ 3.2916, -0.3141]])

In [46]:
b

tensor([[ 0.2538,  0.6355],
        [-0.2889,  1.0456]])

In [47]:
#cond中的值大于0的值设为a，小于0的值设置为b
torch.where(cond>0,a,b)

tensor([[-0.0753,  0.1795],
        [-0.2889,  1.0456]])

In [48]:
prob = torch.randn(4,10)

In [49]:
idx = prob.topk(dim=1,k=3)

In [50]:
idx

(tensor([[2.0105, 1.6364, 1.3353],
         [2.8976, 1.1542, 0.8733],
         [1.5381, 1.4563, 1.4079],
         [1.7438, 1.0492, 0.8169]]),
 tensor([[1, 7, 8],
         [6, 0, 1],
         [0, 4, 9],
         [6, 5, 1]]))

In [51]:
idx = idx[1]

In [52]:
idx

tensor([[1, 7, 8],
        [6, 0, 1],
        [0, 4, 9],
        [6, 5, 1]])

In [53]:
label = torch.arange(10) + 100

In [54]:
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [58]:
#gather 将label和idx相连接
torch.gather(label.expand(4,10),dim=1,index=idx.long())

tensor([[101, 107, 108],
        [106, 100, 101],
        [100, 104, 109],
        [106, 105, 101]])