In [2]:
import torch

In [3]:
a = torch.linspace(-100,100,10)

In [4]:
a

tensor([-100.0000,  -77.7778,  -55.5556,  -33.3333,  -11.1111,   11.1111,
          33.3333,   55.5555,   77.7778,  100.0000])

In [5]:
torch.sigmoid(a)

tensor([0.0000e+00, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 9.9999e-01,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])

In [6]:
torch.tanh(a)

tensor([-1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
torch.relu(a)

tensor([  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,  11.1111,  33.3333,
         55.5555,  77.7778, 100.0000])

# 求导

In [8]:
from torch.nn import functional as F
x = torch.ones(1)
w = torch.full([1],2)
mse = F.mse_loss(torch.ones(1), x*w)
mse

tensor(1.)

In [10]:
torch.autograd.grad(mse,[w])

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [11]:
w.requires_grad_()

tensor([2.], requires_grad=True)

In [13]:
torch.autograd.grad(mse,[w])

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [14]:
mse = F.mse_loss(torch.ones(1),x*w)
torch.autograd.grad(mse,[w])

(tensor([2.]),)

In [17]:
mse = F.mse_loss(torch.ones(1), x*w)
mse.backward()

In [18]:
w.grad

tensor([2.])

In [20]:
a = torch.rand(3)
a.requires_grad_()

tensor([0.1839, 0.9770, 0.5914], requires_grad=True)

In [21]:
p = F.softmax(a, dim=0)
p.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [25]:
p = F.softmax(a, dim=0)
torch.autograd.grad(p[1],[a],retain_graph=True)

(tensor([-0.0995,  0.2490, -0.1495]),)

In [26]:
torch.autograd.grad(p[2],[a])

(tensor([-0.0677, -0.1495,  0.2172]),)